[project]
name = "20260211-langchain"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "deepagents>=0.4.0",
    "langchain-aws>=1.2.5",
    "langchain-google-vertexai>=3.2.2",
    "langchain-openai>=1.1.10",
    "pydantic>=2.12.5",
    "tavily-python>=0.7.21",
]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
]

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "INFO"
log_cli_format = "%(asctime)s.%(msecs)03d %(levelname)-8s %(name)s:%(filename)s:%(lineno)d %(message)s"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
