[project]
name = "20260423-deploy-gcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "a2a-sdk[http-server]>=0.3.0",
    "cloudpickle==3.0",
    "google-cloud-aiplatform[adk,agent-engines]>=1.148.1",
    "uvicorn>=0.46.0",
]
